apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-prd
  namespace: sonarqube
  labels:
    app: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:10-community
        envFrom:
          - configMapRef:
              name: sonarqube-config
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  type: ClusterIP
  ports:
  - port: 9000
    name: http
    protocol: TCP
    targetPort: 9000
  selector:
    app: sonarqube
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarqube
  namespace: sonarqube
  annotations:
    konghq.com/strip-path: "false"  # Mantém "/" como raiz no Kong
    konghq.com/preserve-host: "true"  # Preserva o host no request
spec:
  ingressClassName: kong
  rules:
  - host: sonar.meta.com.br
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: sonarqube
            port:
              number: 9000